import 'server-only';
import { and, eq, sql } from 'drizzle-orm';
import { getDb, mediaUsage } from '@/lib/db';
import { getUserEntitlements } from '@/lib/billing/entitlements';
import type { User } from '@/lib/db';

// Monthly AI-video usage tracking + quota checks. MUAPI video generation spends
// real credits, so each plan caps videos/month (lib/billing/plans.ts
// videoMonthly). Images are FREE (Pollinations) and are never counted here.
//
// The counter is keyed by (userId, 'YYYY-MM') in UTC, so it resets naturally at
// the start of each calendar month with no cron/job needed.

/** Current period key 'YYYY-MM' in UTC. */
export function currentPeriod(now: Date = new Date()): string {
  return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}`;
}

/** Videos already generated by this user in the current month. */
export function videoUsedThisMonth(userId: string, now: Date = new Date()): number {
  const row = getDb()
    .select({ n: mediaUsage.videoCount })
    .from(mediaUsage)
    .where(and(eq(mediaUsage.userId, userId), eq(mediaUsage.period, currentPeriod(now))))
    .get();
  return row?.n ?? 0;
}

export interface VideoQuota {
  /** null = unlimited (superadmin only). */
  limit: number | null;
  used: number;
  /** null = unlimited. Never negative. */
  remaining: number | null;
  allowed: boolean;
}

/** Resolve the user's video quota + usage for the current month. */
export function videoQuota(user: User, now: Date = new Date()): VideoQuota {
  const limit = getUserEntitlements(user).limits.videoMonthly;
  const used = videoUsedThisMonth(user.id, now);
  if (limit === null) return { limit: null, used, remaining: null, allowed: true };
  const remaining = Math.max(0, limit - used);
  return { limit, used, remaining, allowed: remaining > 0 };
}

/** Atomically add one to the user's monthly video counter (upsert). */
export function recordVideoGenerated(userId: string, now: Date = new Date()): void {
  const period = currentPeriod(now);
  getDb()
    .insert(mediaUsage)
    .values({ userId, period, videoCount: 1, updatedAt: now })
    .onConflictDoUpdate({
      target: [mediaUsage.userId, mediaUsage.period],
      set: { videoCount: sql`${mediaUsage.videoCount} + 1`, updatedAt: now },
    })
    .run();
}
